### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by Z-fly** [gengwenxuan/tieba4j#1]
新增环境变量，用于控制是否使用推送加。
例如在失败为零的情况下，不使用推送。

**Comment by gengwenxuan** [comment]
会考虑去掉推送加的强制判定

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/122867330-e3aa3700-d35b-11eb-99e7-f866ea8bf2f7.png)
我的意思是，没有失败的就不用推送通知给我了

**Comment by Z-fly** [comment]
在要签到失败的情况下推送通知过来

**Comment by gengwenxuan** [comment]
我怕代码会出现问题，所以设置了推送，想以每天是否收到推送来判断签到正常，所以可能不太会去优化这个

**Comment by Z-fly** [comment]
这其实不叫优化了，这叫功能。
现在要么一直推送，要么就不推送，让用户自行定义推送设置，这是一个需求吧。
还有要相信程序(程序员)的稳健性。现在问题要么是服务器端问题，要么是cookies问题，代码在通过测试后基本不会出问题，问题基本都是运行时错误。

**Comment by gengwenxuan** [comment]
增加ERROR_SEND开关控制
